name: Deploy to gh-pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean gh-pages branch
        run: |
          git checkout gh-pages
          git pull
          git rm -r .
          git commit -m "Clean gh-pages branch"
          git push

      - name: Build project
        run: npm install
      - run: npm run build

      - name: Deploy to gh-pages
        run: |
          git checkout gh-pages
          git pull
          cp -r build/* .
          git add .
          git commit -m "Deploy to gh-pages"
          git push